### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "rames",
    "company": "D Company ",
    "address": "Oslo",
    "phone": "245234232433",
    "email": "rames@gmail.com",
    "password": "ertsdfsdfe3442222"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "rames@gmail.com",
    "password": "pasord123"
}


### Get a user profile endpoint
GET  http://localhost:3001/v1/user/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjcyMjg3MywiZXhwIjoxNjIyNzI1ODczfQ.mzMEpWbGveq06a3ePCXLZFXQCUmY136x-bJO08B1-xk

### Token routers

### Get refreshed token
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjcyMjg3MywiZXhwIjoxNjI1MzE0ODczfQ.n7u5lUOQKjvRU0TpNntyCqo-rFWP5s-t7IIj-d5R-IM
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjEwOTUzMywiZXhwIjoxNjI0NzAxNTMzfQ.jcWFl9KuNNe8RhqkWimg6HXO0nIq2cwaIcH1aR26yfw

### Password reset request endpoints
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "rames@gmail.com"

}   



### Update new password and endpoint
PATCH  http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "rames@gmail.com",
    "pin":482543,
    "newPassword":"pasord123"

} 


### user logout endpoint
DELETE  http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjcyMjkxOCwiZXhwIjoxNjIyNzI1OTE4fQ.rJt5lh7VD-iVGJ1AREG1KKgX-me4MCk3Q4jZecOUKCs

### Ticket apis

### Open new ticket
POST http://localhost:3001/v1/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjcyMjg3MywiZXhwIjoxNjIyNzI1ODczfQ.mzMEpWbGveq06a3ePCXLZFXQCUmY136x-bJO08B1-xk
### Get single ticket
GET http://localhost:3001/v1/ticket/60aeaedde8e4af39fc1d77b5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjcyMjg3MywiZXhwIjoxNjIyNzI1ODczfQ.mzMEpWbGveq06a3ePCXLZFXQCUmY136x-bJO08B1-xk


### Reply message to the ticket
PUT http://localhost:3001/v1/ticket/60aeaedde8e4af39fc1d77b5
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjcyMjg3MywiZXhwIjoxNjIyNzI1ODczfQ.mzMEpWbGveq06a3ePCXLZFXQCUmY136x-bJO08B1-xk
Content-Type: application/json
{
    "message": "this is the 333 reply",
    "sender":"Gopal"
}

### Close the ticket
PATCH http://localhost:3001/v1/ticket/close-ticket/60aeaedde8e4af39fc1d77b5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjcyMjkxOCwiZXhwIjoxNjIyNzI1OTE4fQ.rJt5lh7VD-iVGJ1AREG1KKgX-me4MCk3Q4jZecOUKCs

### Delete the ticket
DELETE  http://localhost:3001/v1/ticket/60aeaedde8e4af39fc1d77b5
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjcyMjkxOCwiZXhwIjoxNjIyNzI1OTE4fQ.rJt5lh7VD-iVGJ1AREG1KKgX-me4MCk3Q4jZecOUKCs
