### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "rames",
    "company": "D Company ",
    "address": "Oslo",
    "phone": "245234232433",
    "email": "rames@gmail.com",
    "password": "ertsdfsdfe3442222"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "rames@gmail.com",
    "password": "pasord123"
}


### Get a user profile endpoint
GET  http://localhost:3001/v1/user/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjEwODEzOCwiZXhwIjoxNjIyMTA5MDM4fQ.hc6teWcLPl0bvzdGlPGDVxLbdnor1PA4YC9hESbhcmw


### Token routers

### Get refreshed token
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjEwOTUzMywiZXhwIjoxNjI0NzAxNTMzfQ.jcWFl9KuNNe8RhqkWimg6HXO0nIq2cwaIcH1aR26yfw
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjEwOTUzMywiZXhwIjoxNjI0NzAxNTMzfQ.jcWFl9KuNNe8RhqkWimg6HXO0nIq2cwaIcH1aR26yfw

### Password reset request endpoints
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "rames@gmail.com"

}   



### Update new password and endpoint
PATCH  http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "rames@gmail.com",
    "pin":482543,
    "newPassword":"pasord123"

} 


### user logout endpoint
DELETE  http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjY2NDkyNSwiZXhwIjoxNjIyNjY3OTI1fQ.e-WUc2DEffAC73CvNEiP2riRieAsU9L6F83hrQYqO80

### Ticket apis

### Open new ticket

POST http://localhost:3001/v1/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjY2NTAwNiwiZXhwIjoxNjIyNjY4MDA2fQ.JAUAR8rnaKec2j8UuIPi0tTKHL-z6ubIpW1ImmgpwmE
Content-Type: application/json
{
    "subject": "Form issue",
    "sender":"Dnes",
    "message": "1 contact form not working. Please fix it as soon as possible"
}

### Get all the tickets

GET http://localhost:3001/v1/ticket
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjY2NTAwNiwiZXhwIjoxNjIyNjY4MDA2fQ.JAUAR8rnaKec2j8UuIPi0tTKHL-z6ubIpW1ImmgpwmE

### Get single ticket
GET http://localhost:3001/v1/ticket/60aeaedde8e4af39fc1d77b5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjY2NTAwNiwiZXhwIjoxNjIyNjY4MDA2fQ.JAUAR8rnaKec2j8UuIPi0tTKHL-z6ubIpW1ImmgpwmE


### Reply message to the ticket
PUT http://localhost:3001/v1/ticket/60aeaedde8e4af39fc1d77b5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjY2NTAwNiwiZXhwIjoxNjIyNjY4MDA2fQ.JAUAR8rnaKec2j8UuIPi0tTKHL-z6ubIpW1ImmgpwmE
Content-Type: application/json
{
    "message": "this is the 222 reply",
    "sender":"Dnes"
}

### Close the ticket
PATCH http://localhost:3001/v1/ticket/close-ticket/60aeaedde8e4af39fc1d77b5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjY2NTAwNiwiZXhwIjoxNjIyNjY4MDA2fQ.JAUAR8rnaKec2j8UuIPi0tTKHL-z6ubIpW1ImmgpwmE

### Delete the ticket
DELETE  http://localhost:3001/v1/ticket/60aeaedde8e4af39fc1d77b5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjY2NTAwNiwiZXhwIjoxNjIyNjY4MDA2fQ.JAUAR8rnaKec2j8UuIPi0tTKHL-z6ubIpW1ImmgpwmE
