### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "rames",
    "company": "D Company ",
    "address": "Oslo",
    "phone": "245234232433",
    "email": "rames@gmail.com",
    "password": "ertsdfsdfe3442222"
}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "rames@gmail.com",
    "password": "pasord13"
}


### Get a user profile endpoint
GET  http://localhost:3001/v1/user/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjEwODEzOCwiZXhwIjoxNjIyMTA5MDM4fQ.hc6teWcLPl0bvzdGlPGDVxLbdnor1PA4YC9hESbhcmw


### Token routers

### Get refreshed token
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjEwOTUzMywiZXhwIjoxNjI0NzAxNTMzfQ.jcWFl9KuNNe8RhqkWimg6HXO0nIq2cwaIcH1aR26yfw
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjEwOTUzMywiZXhwIjoxNjI0NzAxNTMzfQ.jcWFl9KuNNe8RhqkWimg6HXO0nIq2cwaIcH1aR26yfw

### Password reset request endpoints
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "rames@gmail.com"

}   



### Update new password and endpoint
PATCH  http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email": "rames@gmail.com",
    "pin":482543,
    "newPassword":"pasord123"

} 


### user logout endpoint
DELETE  http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbWVzQGdtYWlsLmNvbSIsImlhdCI6MTYyMjIxMTE0NywiZXhwIjoxNjIyMjEyOTQ3fQ.TzY7PT1GidQMW6iB5-XLefmI0xwV5UDaK_oDkCRtJ08


